### ISSUE TITLE
Android: No scanning when app is in background

### ISSUE THREAD

**Issue by nikita-usichenko** [Driversnote-Dev/react-native-kontaktio#109]
Platform
Android

Expected behavior
The app continues detecting beacons even if the app is in the background

Actual behavior
The scan stops when the app is  in the background

It works correctly on IOS but It does not work on android..
Can someone provide the solution?
PS. I mean exactly background mode, not when the app is killed ( but of course, it will be cool if someone tell and about this)

**Comment by nikita-usichenko** [comment]
Sorry it was my mistake, everything works correctly

**Comment by ycldz** [comment]
what exactly is the problem i have the same problem with android

**Comment by ycldz** [comment]
> Sorry it was my mistake, everything works correctly

what exactly is the problem i have the same problem with android

**Comment by vkozinec** [comment]
@nikita-usichenko Hello, could you please provide example on how you achieved to detect beacons even when app is in background? Thank you.

**Comment by ycldz** [comment]
+

**Comment by ycldz** [comment]
Did anybody do it?

**Comment by ycldz** [comment]
@andrekovac  Can you help me?

**Comment by ycldz** [comment]
@andrekovac  "regionDidExit" works when I lock the screen or close the app. How can I make it work in the background.
