### ISSUE TITLE
Continue to discover beacon when the app is closed

### ISSUE THREAD

**Issue by smartdevdom** [Driversnote-Dev/react-native-kontaktio#14]
Hi i need information about Continue to discover beacon when the app is closed

**Comment by Andruschenko** [comment]
We are currently not using beacons in background mode, so I cannot give you hands-on advice on that. However, please take a look at these instructions of another module. Perhaps it can help you to set up background-mode, but I didn’t test it myself: https://github.com/MacKentoch/react-native-beacons-manager/blob/master/BACKGROUND_MODES.md

**Comment by Andruschenko** [comment]
Duplicate of #53

**Comment by driversnote** [comment]
Hi @smartdevdom. The answer is pretty much here, which is bad news: https://github.com/Driversnote-Dev/react-native-kontaktio/issues/53#issuecomment-576205658
