### ISSUE TITLE
Looking for Light sensor data from iBEEKS (or Eddy stone with light sensor)

### ISSUE THREAD

**Issue by arunraj-qburst** [Driversnote-Dev/react-native-kontaktio#24]
Hi,
We are looking for a solution to fetch the light sensor data along with the telemetry object from an Eddystone beacon which already supports light sensor (Bluvision iBEEK)

We assumes that the telemetry object inside the beacons should provide the additional datas such as light and x,y axis movements. Any suggestions would save us as we are already fed up with the light sensor data!!!

Thanks in Advance,
Arun

**Comment by andrekovac** [comment]
This question seems to be out of scope of this library and is now already quite dated.
