### ISSUE TITLE
Setup guide with Cocoapods

### ISSUE THREAD

**Issue by kiu95** [Driversnote-Dev/react-native-kontaktio#60]
This project provided Podspec file but the setup guide is still about manual link.

Is there any setup guide about Cocoapods (with Kontakt.io iOS SDK installation e.g. https://developer.kontakt.io/mobile/ios/installation/)?

Thanks

**Comment by Andruschenko** [comment]
Documentation for the Cocoapods installation was not yet added.
Feel free to file a PR with the documentation if you successfully get it to run.

**Comment by Andruschenko** [comment]
it now got updated with PR #67 Please give it another try.
