### ISSUE TITLE
Example giving error: 'RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by nylsoo** [Driversnote-Dev/react-native-kontaktio#62]
I tried to run the example code, but got the following error:
`'RCTBridgeModule.h' file not found`

**Comment by AshinePl** [comment]
@nylsoo Have you managed to resolve this problem?
I have a similar one after doing all the steps in the IOS Setup:

> 'React/RCTDefines.h' file not found
> 'RCTBridgeModule.h' file

**Comment by Andruschenko** [comment]
The setup guides got updated in the new version of this lib (`2.7.2.`). Unfortunately the example is a bit outdated by now. Please try with the new minimal example code which you can find in the `README`. It's tested for Android and iOS with RN 0.61

**Comment by Thianzeren** [comment]
<img width="753" alt="Screenshot 2020-04-29 at 9 16 03 AM" src="https://user-images.githubusercontent.com/37324155/80552842-7c645180-89fa-11ea-9764-73f6510c5887.png">

Hey did you manage to resolve the problem? I'm facing the same one that @AshinePl has. This is in my own application, not the example.

**Comment by AshinePl** [comment]
@Thianzeren My problem was with the "framework search paths" I was setting the "header search paths" instead. After I followed the iOS setup manual carefully, everything worked like a charm

**Comment by Thianzeren** [comment]
> @Thianzeren My problem was with the "framework search paths" I was setting the "header search paths" instead. After I followed the iOS setup manual carefully, everything worked like a charm

I’m using react native v0.62.2 with pods, should I still do the steps for the manual installation? I currently only have $(inherited) in my Framework Search Paths

**Comment by Thianzeren** [comment]
Managed to fix this as I found out that I had the KontaktBeacon libraries in both my "linked binary with libraries" and also in my Pods. I removed it from my "linked binary with libraries" and it builds correctly!

**Comment by andrekovac** [comment]
@Thianzeren Great to hear that. You should either follow the automatic install with Pods or the manual install and not mix both.
