### ISSUE TITLE
My app cannot see simulated beacons

### ISSUE THREAD

**Issue by DevQuayle** [Driversnote-Dev/react-native-kontaktio#66]
I have little problem with detect simulated beacons. I try simulate ibeacon from my second phone by Beacon Simulator on android. But my app can't see these beacons, but when I simulate beacon from my macbook, my app see this beacon.

I don't have phisical beacon yet, so I don't tested it.

Maybe have you any idea what I doing wrong ?

**Comment by Andruschenko** [comment]
I use this to use my macbook to simulate a beacon and it works quite well: https://github.com/timd/MactsAsBeacon

**Comment by Andruschenko** [comment]
Since it's working when you simulate a beacon with your macbook, the lib is generally working. Seems to be an issue with your beacon simulator on Android.
