### ISSUE TITLE
lib not working  as expected for iOS 13.3

### ISSUE THREAD

**Issue by nikhilgatewaycorp** [Driversnote-Dev/react-native-kontaktio#69]
hi have integrated lib with my project ,its working for for android and even for ios 12.4.5 (iPhone 6s) but not working in iPhone X (os 13.3),

error:

dyld: Library not loaded: @rpath/KontaktSDK.framework/KontaktSDK
  Referenced from: /private/var/containers/Bundle/Application/18F90787-C083-4D06-9C58-9094014C7D50/BCnDemo.app/BCnDemo
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/18F90787-C083-4D06-9C58-9094014C7D50/BCnDemo.app/Frameworks/KontaktSDK.framework/KontaktSDK: code signature invalid for '/private/var/containers/Bundle/Application/18F90787-C083-4D06-9C58-9094014C7D50/BCnDemo.app/Frameworks/KontaktSDK.framework/KontaktSDK'

any thing i am missing ?

same issue with ios native sample project i faced
thanks in advance

**Comment by Andruschenko** [comment]
It works on my iPhone X (with OS 13.3)

**Comment by Andruschenko** [comment]
How did you install it? Please try the new auto-linking install if you're using RN 0.60+ . I just updated the setup docs for Android and iOS -> It's part of the new version `2.7.2.`

**Comment by nikhilgatewaycorp** [comment]
thanks for quick update . i thinks device not registered with profile, now every thing is working

**Comment by Voxoff** [comment]
@nikhilgatewaycorp can you expand? I get this error on IOS 13.3.1 but I do not on any simulators nor on a device with IOS 12.4.1.

Hope I'm not being slow AF 🙈

**Comment by nikhilgatewaycorp** [comment]
> @nikhilgatewaycorp can you expand on "device not registered with profile"? I get this error on IOS 13.3.1 but I do not on any simulators nor on a device with IOS 12.4.1.
> 
> Hope I'm not being slow AF 🙈

please do this basic steps and let me know
1: use real device only
2 : check info.plist 
3: register your device to your apple account (add device )

then unstall app and install app in device

let me know if still you face issue
