### ISSUE TITLE
Android beacon scanning not working

### ISSUE THREAD

**Issue by adarshraj87** [Driversnote-Dev/react-native-kontaktio#70]
Hi 

I was trying out this library instead of beacon manager, in IOS its all working good, but in android, beacons are not showing up. Btw I'm not using Kontaktio beacons.

**Comment by Amirhossein-Hediehloo** [comment]
same here

**Comment by Amirhossein-Hediehloo** [comment]
> 
> 
> Hi
> 
> I was trying out this library instead of beacon manager, in IOS its all working good, but in android, beacons are not showing up. Btw I'm not using Kontaktio beacons.

Any solution? i just did all the setup and im sure the code is ok but i can't see any beacon created with another phone(as beacon)

**Comment by jazg** [comment]
Can you post your code?

**Comment by Andruschenko** [comment]
Did you use the code from the minimal example in the README?: https://github.com/Driversnote-Dev/react-native-kontaktio#minimal-example

The example app is unfortunately outdated.

**Comment by raulpartida** [comment]
Hi, I have the same problem, I implement the example that is in Readme file and manully config and I can´t see my beacon in the console, I just see the text label.

I'm using: 
*SO: Android 7.0
*RN: 61.2
*Beacon spec: BLE iBeacon 
*react-native-kontaktio: 2.7.2

Any solution?

**Comment by brnyza** [comment]
Here for me, it stopped reading becons, now it's working.

**Comment by andrekovac** [comment]
Just tested. In the current version [v3.1.0](https://github.com/Driversnote-Dev/react-native-kontaktio/releases/tag/v3.1.0) beacon scanning works on Android.

Closing this issue.
