### ISSUE TITLE
Not working on Android 12

### ISSUE THREAD

**Issue by pingumen96** [Driversnote-Dev/react-native-kontaktio#94]
Good morning, I noticed that the library is using an old kontaktio Android sdk which is not compatible with Android 12 due to the new permission management for bluetooth devices.
Would it be possible to upgrade the kontaktio sdk to the version 7.x?
Source: https://github.com/kontaktio/kontakt-android-sdk/commit/b112def23ecfa19bd498541ac917d4db4cf315fc

**Comment by pingumen96** [comment]
My fault, it works.

**Comment by devberkay** [comment]
How did you resolve it? I am especially having problem on Android 12 . @pingumen96

**Comment by pingumen96** [comment]
If I remember well, it is necessary to change the compile target to 31 or something similar
