### ISSUE TITLE
Example App Not Finding Beacons on Android 12

### ISSUE THREAD

**Issue by mjmostachetti** [Driversnote-Dev/react-native-kontaktio#96]
Hey,
I'm running on React Native 0.69.0.
Device: Pixel 3
Does this package work for Android 12? I've tried adding all the correct permissions for Android 12 and it seems to start scanning but the app never registers any events for finding ibeacons.
Thanks

**Comment by anthonyhumphreys** [comment]
Did you get any further with this?

**Comment by andrekovac** [comment]
@JonasWho @martinpoulsen Have you successfully tested the package with **Android v12**?

**Comment by andrekovac** [comment]
@mjmostachetti Great to heat that! The new major version 4 includes the newest Kontakt SDK
